### ISSUE TITLE
Metric Types

### ISSUE THREAD

**Issue by john898** [groupon/spark-metrics#10]
Is it possible to get an example of what/how each type type of metric is used.
Example What is a Gauge and when is it used
Thanks!

**Comment by akakitani** [comment]
@john898 sure, the types of metrics in this library are based on the ones in the Dropwizard library, so I think their documentation would be a good starting point for when to use certain things: http://metrics.dropwizard.io

If you have any specific questions about how those are implemented in this library I can answer that for you

**Comment by john898** [comment]
This is exactly what I was looking for. Thank you.
