### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mkargar** [groupon/spark-metrics#14]
Just tried this for a Java Spark job and got NPE. Any thoughts?

Caused by: java.lang.NullPointerException
	at org.apache.spark.rpc.netty.NettyRpcEndpointRef.send(NettyRpcEnv.scala:520)
	at org.apache.spark.groupon.metrics.SparkMetric$class.sendMetric(SparkMetric.scala:54)
	at org.apache.spark.groupon.metrics.SparkMeter.sendMetric(SparkMetric.scala:137)
	at org.apache.spark.groupon.metrics.SparkMeter.mark(SparkMetric.scala:148)

**Comment by mkargar** [comment]
This caused by instantiating SparkMetric in the driver class of a Spark streaming application. After moving the instantiation to executors I no longer get NPE. However sometimes I get exception complaining a metrics with the same name already exists!

**Comment by kylemede** [comment]
I am having the same issue and would appreciate any guidance you could provide.

Current approach:
- Instantiate the UserMetricsSystem in the executor.
- instantiate the meter metric in the module and bind them as named instances
- inject the named instances into the mappers using Guice.
- inject the mappers into the pipeline

Is there an issue with this approach?  Suggestions?

Thank you for your time!

**Comment by kylemede** [comment]
Answer:

I found the answer myself.  
The metrics need to be wrapped in a class that extends Serializable.  So, I just made one for meter and another for gauge metrics.
