### ISSUE TITLE
Does spark-metrics work for Spark 1.6.2?

### ISSUE THREAD

**Issue by filmonhg** [groupon/spark-metrics#5]
I tried it with the following details: 
import org.apache.spark.groupon.metrics._

//inside main
val sc = new SparkContext(new SparkConf().setAppName("groupon_spark_Metrics_test").setMaster("spark://xx..xx.xx.xx:7077"))

UserMetricsSystem.initialize(sc, "MyMetricNamespace") //this is where its failing 
val counter: SparkCounter = UserMetricsSystem.counter("MyCounter") //also tried it with lazy val  counter

val incrementVals = Seq(1, 2, 3, -1, -2, -3)
    incrementVals.take(5).foreach(i => counter.inc(i))

//I am not sure if I have to print it this way, I wasn't sure with rest API call? Can you explicitely also //mention the port on Spark UI.

println(counter.metricsEndpoint) 

//END of code

OUTPUT (Error) on Spark-submit
//===================================
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/groupon/metrics/UserMetricsSystem

**Comment by akakitani** [comment]
hey @filmonhg, sorry I didn't see this until today! Seems like a dependency management issue, not something specific for 1.6.2. As far as I know the internal APIs between 1.5 and 1.6 should not break this library. If you're still having trouble with this, could you paste the dependency file you use for your build (pom.xml, build.sbt, etc.)?

**Comment by akakitani** [comment]
@filmonhg going to close this, you can include the following dependency to use this library against Spark 1.6:

```xml
<dependency>
    <groupId>com.groupon.dse</groupId>
    <artifactId>spark-metrics_spark-1.x</artifactId>
    <version>2.0.0</version>
</dependency>
```
